### ISSUE TITLE
can't use differents pairs

### ISSUE THREAD

**Issue by CesarPierr** [theophane-droid/8mile#19]

**Comment by theophane-droid** [comment]
Add the ability to take in entry of a DataProvider a list of pairs. 

The data will be returned in a dictionnary as : 

```json
{
"pair1" : "dataframe1",
"pair2": "dataframe2"
}
```

Tasks to do :
- [ ] update dataprovider
- [ ] update datatransformer
- [ ] update dataexporter
- [ ] update trainAE
- [ ] update tests
- [ ] update doc

**Comment by theophane-droid** [comment]
Fixed by 
215cf0a
